// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify MCP connectivity.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-recent-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_recent_blog_posts_default = defineTool2({
  name: "list_recent_blog_posts",
  title: "List recent blog posts",
  description: "Return the most recent published SearchTune OS blog posts (title, slug, excerpt, published date). Read-only public content.",
  inputSchema: {
    limit: z2.number().int().min(1).max(20).optional().describe("How many posts to return (1-20). Defaults to 5.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !anon) {
      return {
        content: [{ type: "text", text: "Backend is not configured." }],
        isError: true
      };
    }
    const n = Math.min(Math.max(limit ?? 5, 1), 20);
    const endpoint = `${url}/rest/v1/blog_posts?select=title,slug,excerpt,published_at&status=eq.published&order=published_at.desc&limit=${n}`;
    const res = await fetch(endpoint, {
      headers: {
        apikey: anon,
        Authorization: `Bearer ${anon}`
      }
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch posts: ${res.status}` }],
        isError: true
      };
    }
    const rows = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { posts: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "searchtune-os-mcp",
  title: "SearchTune OS MCP",
  version: "0.1.0",
  instructions: "Tools for SearchTune OS. Use `echo` to verify connectivity. Use `list_recent_blog_posts` to fetch recent published SearchTune OS blog posts.",
  tools: [echo_default, list_recent_blog_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
